format = """
$username$hostname\
îœ‘ \
$git_branch\
$kubernetes\
\n$directory\
\n$character"""

[directory]
format = "[$path]($style)"
truncation_length = 7
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ğŸ“ "
"Downloads" = "ğŸ“¥ "
"Music" = "ğŸµ "
"Pictures" = "ğŸ“· "


[git_branch]
symbol = 'ğŸŒ± '
truncation_length = 12
truncation_symbol = '...'
ignore_branches = ['master', 'main']


[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'


[kubernetes]
format = 'on [â›µ $context:\($namespace\)](dimmed green) '
disabled = false
contexts = [
    { context_pattern = "nemo-dev-green", style = "green", symbol = "ğŸ’” " },
]

[username]
style_user = 'grey'
style_root = 'black bold'
format = '[$user@]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)[$hostname](grey) '
trim_at = 'nvidia.com'
disabled = false

[python]
disabled = true

[rust]
disabled = true

[nodejs]
disabled = true

[nix_shell]
disabled = true

[terraform]
disabled = true


[package]
disabled = true
